import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const section = (label: string) => ({
  type: "html" as const,
  value: label,
  defaultStyle: true,
  className: "sidebar-section-label",
});

const sidebars: SidebarsConfig = {
  docsSidebar: [
    section("START HERE"),
    {
      type: "category",
      label: "Introduction",
      items: [
        "introduction/index",
        "introduction/choose-a-format",
        "introduction/product-model",
        "introduction/support-matrix",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        "start/index",
        "start/java",
        "start/python",
        "start/cpp",
        "start/go",
        "start/rust",
        "start/javascript",
        "start/csharp",
        "start/swift",
        "start/dart",
        "start/scala",
        "start/kotlin",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Benchmarks",
      items: ["benchmarks/index", "benchmarks/methodology"],
      collapsed: true,
    },
    section("SERIALIZATION PRODUCTS"),
    {
      type: "category",
      label: "Object Serialization",
      items: [
        "object-serialization/index",
        "object-serialization/xlang/index",
        "object-serialization/native",
        "object-serialization/security",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Row Format",
      items: [
        "row-format/index",
        "row-format/standard",
        "row-format/compact",
        "row-format/java",
        "row-format/python",
        "row-format/cpp",
        "row-format/rust",
        "row-format/troubleshooting",
      ],
      collapsed: true,
    },
    {
      type: "category",
      label: "Fory JSON",
      items: [
        "json/index",
        "json/getting-started",
        "json/object-mapping",
        "json/annotations",
        "json/custom-codecs",
        "json/android",
        "json/graalvm",
        "json/security",
        "json/troubleshooting",
      ],
      collapsed: true,
    },
    section("SCHEMA AND CODE GENERATION"),
    {
      type: "category",
      label: "Fory IDL & Compiler",
      items: [
        "compiler/index",
        "compiler/getting-started",
        "compiler/build-integration",
        "compiler/schema-idl",
        "compiler/cli",
        "compiler/protobuf-idl",
        "compiler/flatbuffers-idl",
        "compiler/generated-code/index",
      ],
      collapsed: true,
    },
    section("INTEGRATIONS"),
    {
      type: "category",
      label: "Fory gRPC",
      items: [
        "grpc/index",
        "grpc/architecture",
        "grpc/interoperability",
        "grpc/java",
        "grpc/python",
        "grpc/cpp",
        "grpc/go",
        "grpc/rust",
        "grpc/javascript",
        "grpc/csharp",
        "grpc/dart",
        "grpc/scala",
        "grpc/kotlin",
        "grpc/troubleshooting",
      ],
      collapsed: true,
    },
    section("RESOURCES"),
    {
      type: "category",
      label: "Development",
      items: [
        "development/index",
        "development/building",
        "development/cpp-debugging",
      ],
      collapsed: true,
    },
  ],

  javaObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/java/index",
    section("SERIALIZATION MODES"),
    "object-serialization/java/xlang",
    "object-serialization/java/native",
    section("COMMON"),
    "object-serialization/java/core-api",
    "object-serialization/java/configuration",
    "object-serialization/java/type-registration",
    "object-serialization/java/schema-evolution",
    "object-serialization/java/schema-metadata",
    "object-serialization/java/custom-serializers",
    section("JAVA FEATURES"),
    "object-serialization/java/advanced-features",
    "object-serialization/java/compression",
    "object-serialization/java/object-copy",
    "object-serialization/java/jdk-serialization",
    "object-serialization/java/static-generated-serializers",
    section("PLATFORM"),
    "object-serialization/java/android",
    "object-serialization/java/graalvm",
    section("OPERATE"),
    "object-serialization/java/virtual-threads",
    "object-serialization/security",
    "object-serialization/java/troubleshooting",
  ],

  pythonObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/python/index",
    section("SERIALIZATION MODES"),
    "object-serialization/python/xlang",
    "object-serialization/python/native",
    section("COMMON"),
    "object-serialization/python/core-api",
    "object-serialization/python/configuration",
    "object-serialization/python/type-registration",
    "object-serialization/python/schema-evolution",
    "object-serialization/python/schema-metadata",
    "object-serialization/python/custom-serializers",
    section("PYTHON FEATURES"),
    "object-serialization/python/functions-classes-methods",
    "object-serialization/python/serialization-hooks",
    "object-serialization/python/out-of-band",
    "object-serialization/python/numpy-integration",
    section("OPERATE"),
    "object-serialization/security",
    "object-serialization/python/troubleshooting",
  ],

  cppObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/cpp/index",
    section("SERIALIZATION MODES"),
    "object-serialization/cpp/xlang",
    "object-serialization/cpp/native",
    section("COMMON"),
    "object-serialization/cpp/core-api",
    "object-serialization/cpp/configuration",
    "object-serialization/cpp/type-registration",
    "object-serialization/cpp/schema-evolution",
    "object-serialization/cpp/schema-metadata",
    "object-serialization/cpp/polymorphism",
    "object-serialization/cpp/custom-serializers",
    "object-serialization/cpp/supported-types",
    section("OPERATE"),
    "object-serialization/security",
  ],

  goObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/go/index",
    section("SERIALIZATION MODES"),
    "object-serialization/go/xlang",
    "object-serialization/go/native",
    section("COMMON"),
    "object-serialization/go/core-api",
    "object-serialization/go/configuration",
    "object-serialization/go/type-registration",
    "object-serialization/go/schema-evolution",
    "object-serialization/go/schema-metadata",
    "object-serialization/go/references",
    "object-serialization/go/custom-serializers",
    "object-serialization/go/supported-types",
    section("OPERATE"),
    "object-serialization/go/thread-safety",
    "object-serialization/security",
    "object-serialization/go/troubleshooting",
  ],

  rustObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/rust/index",
    section("SERIALIZATION MODES"),
    "object-serialization/rust/xlang",
    "object-serialization/rust/native",
    section("COMMON"),
    "object-serialization/rust/core-api",
    "object-serialization/rust/configuration",
    "object-serialization/rust/type-registration",
    "object-serialization/rust/schema-evolution",
    "object-serialization/rust/schema-metadata",
    "object-serialization/rust/references",
    "object-serialization/rust/polymorphism",
    "object-serialization/rust/external-types",
    "object-serialization/rust/custom-serializers",
    section("OPERATE"),
    "object-serialization/security",
    "object-serialization/rust/troubleshooting",
  ],

  javascriptObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/javascript/index",
    section("SERIALIZATION MODE"),
    "object-serialization/javascript/xlang",
    section("COMMON"),
    "object-serialization/javascript/core-api",
    "object-serialization/javascript/configuration",
    "object-serialization/javascript/type-registration",
    "object-serialization/javascript/schema-evolution",
    "object-serialization/javascript/schema-metadata",
    "object-serialization/javascript/references",
    "object-serialization/javascript/supported-types",
    section("OPERATE"),
    "object-serialization/security",
    "object-serialization/javascript/troubleshooting",
  ],

  csharpObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/csharp/index",
    section("SERIALIZATION MODE"),
    "object-serialization/csharp/xlang",
    section("COMMON"),
    "object-serialization/csharp/core-api",
    "object-serialization/csharp/configuration",
    "object-serialization/csharp/type-registration",
    "object-serialization/csharp/schema-evolution",
    "object-serialization/csharp/schema-metadata",
    "object-serialization/csharp/references",
    "object-serialization/csharp/external-types",
    "object-serialization/csharp/custom-serializers",
    "object-serialization/csharp/supported-types",
    section("OPERATE"),
    "object-serialization/csharp/thread-safety",
    "object-serialization/security",
    "object-serialization/csharp/troubleshooting",
  ],

  swiftObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/swift/index",
    section("SERIALIZATION MODE"),
    "object-serialization/swift/xlang",
    section("COMMON"),
    "object-serialization/swift/core-api",
    "object-serialization/swift/configuration",
    "object-serialization/swift/type-registration",
    "object-serialization/swift/schema-evolution",
    "object-serialization/swift/schema-metadata",
    "object-serialization/swift/references",
    "object-serialization/swift/polymorphism",
    "object-serialization/swift/external-types",
    "object-serialization/swift/custom-serializers",
    section("OPERATE"),
    "object-serialization/security",
    "object-serialization/swift/troubleshooting",
  ],

  dartObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/dart/index",
    section("SERIALIZATION MODE"),
    "object-serialization/dart/xlang",
    section("COMMON"),
    "object-serialization/dart/core-api",
    "object-serialization/dart/code-generation",
    "object-serialization/dart/configuration",
    "object-serialization/dart/type-registration",
    "object-serialization/dart/schema-evolution",
    "object-serialization/dart/schema-metadata",
    "object-serialization/dart/inheritance",
    "object-serialization/dart/external-types",
    "object-serialization/dart/custom-serializers",
    "object-serialization/dart/supported-types",
    section("PLATFORM"),
    "object-serialization/dart/web-platform-support",
    section("OPERATE"),
    "object-serialization/security",
    "object-serialization/dart/troubleshooting",
  ],

  scalaObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/scala/index",
    section("SERIALIZATION MODES"),
    "object-serialization/scala/xlang",
    "object-serialization/scala/native",
    section("COMMON"),
    "object-serialization/scala/configuration",
    "object-serialization/scala/schema-metadata",
    section("SCALA FEATURES"),
    "object-serialization/scala/default-values",
    section("OPERATE"),
    "object-serialization/security",
  ],

  kotlinObjectSerializationSidebar: [
    section("ORIENT"),
    "object-serialization/kotlin/index",
    section("SERIALIZATION MODES"),
    "object-serialization/kotlin/xlang",
    "object-serialization/kotlin/native",
    section("COMMON"),
    "object-serialization/kotlin/configuration",
    "object-serialization/kotlin/schema-metadata",
    section("KOTLIN FEATURES"),
    "object-serialization/kotlin/default-values",
    "object-serialization/kotlin/static-generated-serializers",
    section("OPERATE"),
    "object-serialization/security",
  ],

  generatedCodeSidebar: [
    section("GENERATED CODE"),
    "compiler/generated-code/index",
    section("OUTPUT RUNTIMES"),
    "compiler/generated-code/java",
    "compiler/generated-code/python",
    "compiler/generated-code/cpp",
    "compiler/generated-code/go",
    "compiler/generated-code/rust",
    "compiler/generated-code/javascript",
    "compiler/generated-code/csharp",
    "compiler/generated-code/swift",
    "compiler/generated-code/dart",
    "compiler/generated-code/scala",
    "compiler/generated-code/kotlin",
  ],

  specificationSidebar: [{ type: "autogenerated", dirName: "specification" }],
  communitySidebar: [{ type: "autogenerated", dirName: "community" }],
};

export default sidebars;
