import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const category = (label: string, dirName: string) => ({
  type: "category" as const,
  label,
  collapsible: true,
  collapsed: true,
  items: [{ type: "autogenerated" as const, dirName }],
});

const sidebars: SidebarsConfig = {
  docsSidebar: [
    category("Introduction", "introduction"),
    category("Getting Started", "start"),
    category("Benchmarks", "benchmarks"),
    category("Object Serialization", "object-serialization"),
    category("Row Format", "row-format"),
    category("Fory JSON", "json"),
    category("Fory IDL & Compiler", "compiler"),
    category("Fory gRPC", "grpc"),
    category("Development", "development"),
  ],
  specificationSidebar: [{ type: "autogenerated", dirName: "specification" }],
  communitySidebar: [{ type: "autogenerated", dirName: "community" }],
};

export default sidebars;
